// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rugkunwrkoknqiquykqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1Z2t1bndya29rbnFpcXV5a3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5ODI3MjMsImV4cCI6MjA1MjU1ODcyM30.Wja_Jqs9oj80dpVsbTv8Cx1Fr4AxL5xkFUcfLzq3P9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);